### ISSUE TITLE
Error on rake db:migrate:squash

### ISSUE THREAD

**Issue by lypborges** [ka8725/migration_data#10]
Hi,

First, nice gem. ;) . 

I try to run ```rake db:migrate:squash```, but i got this error:

```
ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/migration.rb:853:in `current_version'
/usr/local/rvm/gems/ruby-2.2.2/gems/migration_data-0.2.0/lib/migration_data/squash.rb:34:in `current_version'
/usr/local/rvm/gems/ruby-2.2.2/gems/migration_data-0.2.0/lib/migration_data/squash.rb:46:in `migration_file_name'
/usr/local/rvm/gems/ruby-2.2.2/gems/migration_data-0.2.0/lib/migration_data/squash.rb:13:in `squash_schema'
/usr/local/rvm/gems/ruby-2.2.2/gems/migration_data-0.2.0/lib/migration_data/squash.rb:7:in `call'
/usr/local/rvm/gems/ruby-2.2.2/gems/migration_data-0.2.0/lib/tasks/db.rake:7:in `block (3 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/rvm/rubies/ruby-2.2.2/bin/rake:33:in `<main>'
Tasks: TOP => db:migrate:squash
```

if I run ```rails c``` it's everything working. I think, it's related to this

https://github.com/rails/rails/issues/18359

But I'm not sure. Do you have any idea what can be?

**Comment by ka8725** [comment]
Hi, @lypborges. Try to increase connections pull - https://devcenter.heroku.com/articles/concurrency-and-database-connections

Some other threads were working when you tried to run the task. Checkout the example - https://gist.github.com/erichurst/961978#file-database-yml-example-mysql2-L2-L13

This is the `pool` key.

**Comment by lypborges** [comment]
@ka8725 I increase to 15 and get the same error. If a try select count(*) from pg_stat_activity where pid <> pg_backend_pid()  and usename = current_user; gives me 0 connection. Any other tip?

tks! ;)

**Comment by ka8725** [comment]
Open your `rails c` and paste the the following code: `::ActiveRecord::Migrator.current_version`
What the result?

**Comment by ka8725** [comment]
@lypborges could you install the gem from the master branch? Just add the line in Gemfile:

```ruby
gem 'migration_data', github: 'ka8725/migration_data'
```

And run then `bundle install`.

**Comment by lypborges** [comment]
Hi,

I updated and the same error. I also, try to run both commands, the old and new one.

```
::ActiveRecord::Migrator.current_version(::ActiveRecord::Base.connection)
::ActiveRecord::Migrator.current_version

in both cases I get the same result.

  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
=> 20151230230359
```

**Comment by ka8725** [comment]
Does the `rake db:migrate` command work?

**Comment by lypborges** [comment]
yes.

**Comment by ka8725** [comment]
The issues exists because the ActiveRecord connection can't be established automatically. Could you try to paste this line `ActiveRecord::Base.establish_connection` [here](https://github.com/ka8725/migration_data/blob/master/lib/tasks/db.rake#L6). (In the line before `MigrationData::Squash.new.call`). `open /usr/local/rvm/gems/ruby-2.2.2/gems/migration_data-0.2.0/lib/tasks/db.rake`, edit and save it. Later you will be able to reset the change with the `gem pristine migration_data` [command](http://guides.rubygems.org/command-reference/#gem-pristine).

**Comment by ka8725** [comment]
@lypborges or please try update the gem with master branch. It should work now. If it still doesn't work there should be more verbose exception saying what the problem.

**Comment by lypborges** [comment]
```
ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: []
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection'
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:211:in `resolve_connection'
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:169:in `spec'
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/vagrant/.bundler/ruby/2.2.0/migration_data-8332fd1c7e6e/lib/tasks/db.rake:7:in `block (3 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/rvm/rubies/ruby-2.2.2/bin/rake:33:in `<main>'
Tasks: TOP => db:migrate:squash
vagrant@vagrant-ubuntu-trusty-64:/vagrant/app$ 
```

My database.yml

````development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: maestrosales_development
  pool:     15
  username: postgres
  password: xxxxx
  template: template0
```

**Comment by ka8725** [comment]
That's very weird. Accordingly to the exception I only can give you a hint what is incorrect. The problem is concerning reading config for the development environment. I guess it can be because of:
- incorrect path for the `database.yml` file;
- incorrect structure of the yml file;
- there is no `development` section in the `database.yml`;
- there is another gem in your project that breaks Rails loading process (or the break can be because of the code in the project that you are trying to run);
- some other issue concerning ActiveRecord :)

So, in order to reduce the search path could I ask you to create a new rails application from scratch on this machine? `rails new -d postgresql test-migration-data`. Paste the gem in its Gemfile there and install it, configure connection to the DB, create a migration: `rake db:create && rails g migration User && rake db:migrate` and run the `rake db:migrate:squash`. Thanks in advance!

**Comment by lypborges** [comment]
Same error, my database.yml it's like this.

```
default: &default
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool:     15
  username: postgres
  password: vagrant
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling

development:
  <<: *default
  database: test-migration-data_development
```

Don`t worry. I will try with another activerecord version. Tks again.

**Comment by profsmallpine** [comment]
@ka8725 I experienced this same problem, using `activerecord 4.1.7`. I tried adding `ActiveRecord::Base.establish_connection` line where specified and got the same error: `ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: []`. I also tried specifying the master branch `gem 'migration_data', github: 'ka8725/migration_data'`.

**Comment by profsmallpine** [comment]
@ka8725 @lypborges I ended up using `https://github.com/jalkoby/squasher` as a standalone helper to squash the migrations and it worked well.

**Comment by stefanosc** [comment]
@ka8725 I just wanted to report that I am having a similar issue, using the latest version
`ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base`

The worst thing is that it deleted all my migrations and did nothing, god bless git
Let me know if there is anything useful I can do to help debug this, so that others don't experience it.
Thank you!

**Comment by ka8725** [comment]
@stefanosc seems your case is not the same as others. Could you provide the full backtrace?

**Comment by stefanosc** [comment]
Thank you @ka8725 here we go:

```
❯❯❯ rake db:migrate:squash --trace                                                                              master ✭ ✱
** Invoke db:migrate:squash (first_time)
** Execute db:migrate:squash
rake aborted!
ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/activerecord-4.2.5.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/activerecord-4.2.5.1/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:853:in `current_version'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/bundler/gems/migration_data-446953bd74d7/lib/migration_data/squash.rb:34:in `current_version'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/bundler/gems/migration_data-446953bd74d7/lib/migration_data/squash.rb:46:in `migration_file_name'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/bundler/gems/migration_data-446953bd74d7/lib/migration_data/squash.rb:13:in `squash_schema'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/bundler/gems/migration_data-446953bd74d7/lib/migration_data/squash.rb:7:in `call'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/bundler/gems/migration_data-446953bd74d7/lib/tasks/db.rake:7:in `block (3 levels) in <top (required)>'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/bin/rake:23:in `load'
/usr/local/var/rbenv/versions/2.3.0/gemsets/value_letters/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate:squash
```

Could it be that the migrations are not all there? In the beginning of this project we took an initial db schema and loaded, then added migrations from then on. rake db:migrate on a new db won't work because some migrations refer to tables that don't exist yet.

**Comment by ka8725** [comment]
No, it couldn't. This exception means only one - the connection to DB wasn't established. Eventually I caught the exception in a new bootstrapped application. Will fix it soon, thanks, guys, for your cooperation!

**Comment by ka8725** [comment]
Guys, could you install the gem from master branch and test your applications. Are there still issues? Thanks!

**Comment by stefanosc** [comment]
@ka8725 thank you! here we go:
```
❯❯❯ rake db:migrate:squash --trace                                                                              master ✭ ✱
** Invoke db:migrate:squash (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate:squash
```
Great ! :+1:  :smile:
