### ISSUE TITLE
NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by Vizkrig** [ka8725/migration_data#11]
When I issued jruby -S rake db:migrate:squash on my Rubymine rails project I got an error saying NoMethodError: undefined method `each' for nil:NilClass.

Here is the trace:

>jruby -S rake db:migrate:squash --trace
** Invoke db:migrate:squash (first_time)
** Execute db:migrate:squash
rake aborted!
NoMethodError: undefined method `each' for nil:NilClass
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/migration_data-0.2.0/lib/migration_data/squash.rb:28:in `remove_all_old_migrations'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/migration_data-0.2.0/lib/migration_data/squash.rb:6:in `call'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/migration_data-0.2.0/lib/tasks/db.rake:7:in `(root)'
org/jruby/RubyProc.java:271:in `call'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
c:/jruby-1.7.12/lib/ruby/2.0/monitor.rb:211:in `mon_synchronize'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
c:/jruby-1.7.12/lib/ruby/gems/shared/gems/rake-10.4.2/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
c:/jruby-1.7.12/bin/rake:23:in `(root)'
Tasks: TOP => db:migrate:squash

**Comment by ka8725** [comment]
Unfortunately I don't have Windows environment. Could  you try the following: open rails console and paste there the code: `::ActiveRecord::Tasks::DatabaseTasks.migrations_paths`. What the result?

**Comment by ka8725** [comment]
Closing the issue due to no activity.
