### ISSUE TITLE
How to use migration_data for seeding test db?

### ISSUE THREAD

**Issue by fsauter** [ka8725/migration_data#33]
Hi together,

I've the use case that I would like to seed my test db with the data methods provided by this gem. However after the first run, the database is cleared and nothing is left... :) I use minitest (rails5.1 new system tests) together with capybara. Do you have any idea how I could run only the "data" methods before each system test run without dropping the whole db?

Greetings Florian

**Comment by ka8725** [comment]
Hi there, to be honest I have no idea why it did clean your DB. It depends on the data methods you wrote, I suspect. But as far as I see you have configured your test environment in so way that it clears DB after/before first example run. Commonly people use this [gem](https://github.com/DatabaseCleaner/database_cleaner). It's possible to configure it to have some particular tables not cleaned or even all of them. But in my opinion, it's not a good idea (it depends on the data though).

**Comment by fsauter** [comment]
Hi @ka8725,

I blocked the database while running my tests and could follow now what's happing. So rails is doing a `db:test:load => db:test:purge` before each run with `bin/rails test:system`. Afterwards it is recreating the database using `schema.rb` which does not contain the initial data inserted by the `data` method of this gem.

I think I'll handle it by "overriding" both db tasks as mentioned in this comment: https://stackoverflow.com/a/19491334/1544645

... You might have a better idea? Otherwise we can close this issue since this gem is doing his things totally correct.

Here is the stack trace if you're interested.
```
PG::ObjectInUse: ERROR:  database "amos_test" is being accessed by other users
DETAIL:  There is 1 other session using the database.
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activesupport-5.1.5/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:54:in `drop_database'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/postgresql_database_tasks.rb:32:in `drop'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/postgresql_database_tasks.rb:45:in `purge'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:198:in `purge'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/railties/databases.rake:329:in `block (3 levels) in <top (required)>'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/railties/databases.rake:335:in `block (3 levels) in <top (required)>'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/railties-5.1.5/lib/rails/command.rb:46:in `invoke'
/Users/FSA/.rvm/gems/ruby-2.4.3/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:test:load => db:test:purge
```

.. and thanks for the quick answer above :)!

**Comment by ka8725** [comment]
Probably, this is the PR can solve the issue: https://github.com/ka8725/migration_data/pull/37

**Comment by ka8725** [comment]
Done
